FROM alpine:latest
CMD echo "+-------------------------------------------------+" \
&& echo "|   Universidad Cooperativa de Colombia - 2024    |" \
&& echo "+-------------------------------------------------+" \
&& echo "| Att HADRIAN, Saludo                             |" \
&& echo "+-------------------------------------------------+"