package co.edu.campusucc.sd.modelo;
// Generated 16/03/2020 09:12:15 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private String idPais;
	private String nombre;
	private String gentilicioNacional;
	private Set clientes = new HashSet(0);

	public Pais() {
	}

	public Pais(String idPais, String nombre) {
		this.idPais = idPais;
		this.nombre = nombre;
	}

	public Pais(String idPais, String nombre, String gentilicioNacional, Set clientes) {
		this.idPais = idPais;
		this.nombre = nombre;
		this.gentilicioNacional = gentilicioNacional;
		this.clientes = clientes;
	}

	public String getIdPais() {
		return this.idPais;
	}

	public void setIdPais(String idPais) {
		this.idPais = idPais;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getGentilicioNacional() {
		return this.gentilicioNacional;
	}

	public void setGentilicioNacional(String gentilicioNacional) {
		this.gentilicioNacional = gentilicioNacional;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

}
