package co.edu.campusucc.sd.modelo;
// Generated 16/03/2020 09:12:15 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento implements java.io.Serializable {

	private String idTipoDocumento;
	private String nombreDocumento;
	private Set clientes = new HashSet(0);

	public TipoDocumento() {
	}

	public TipoDocumento(String idTipoDocumento, String nombreDocumento) {
		this.idTipoDocumento = idTipoDocumento;
		this.nombreDocumento = nombreDocumento;
	}

	public TipoDocumento(String idTipoDocumento, String nombreDocumento, Set clientes) {
		this.idTipoDocumento = idTipoDocumento;
		this.nombreDocumento = nombreDocumento;
		this.clientes = clientes;
	}

	public String getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(String idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public String getNombreDocumento() {
		return this.nombreDocumento;
	}

	public void setNombreDocumento(String nombreDocumento) {
		this.nombreDocumento = nombreDocumento;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

}
