package co.edu.campusucc.sd.modelo;
// Generated 16/03/2020 09:12:15 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TipoCliente generated by hbm2java
 */
public class TipoCliente implements java.io.Serializable {

	private String idTipoCliente;
	private String nombre;
	private Set clientes = new HashSet(0);

	public TipoCliente() {
	}

	public TipoCliente(String idTipoCliente, String nombre) {
		this.idTipoCliente = idTipoCliente;
		this.nombre = nombre;
	}

	public TipoCliente(String idTipoCliente, String nombre, Set clientes) {
		this.idTipoCliente = idTipoCliente;
		this.nombre = nombre;
		this.clientes = clientes;
	}

	public String getIdTipoCliente() {
		return this.idTipoCliente;
	}

	public void setIdTipoCliente(String idTipoCliente) {
		this.idTipoCliente = idTipoCliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

}
