ALTER SESSION SET CONTAINER=ORCL;
ALTER SESSION SET CURRENT_SCHEMA=banco_user;

CREATE TABLE dummy_table (
	id NUMERIC(3) NOT NULL,
	"name" varchar(30) NULL
);

SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS current_schema FROM dual;