package co.edu.campusucc.sd.modelo;
// Generated 16/03/2020 09:12:15 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;

/**
 * Biometria generated by hbm2java
 */
public class Biometria implements java.io.Serializable {

	private BigInteger idBiometria;
	private Cliente cliente;
	private byte[] bio01;

	public Biometria() {
	}

	public Biometria(BigInteger idBiometria) {
		this.idBiometria = idBiometria;
	}

	public Biometria(BigInteger idBiometria, Cliente cliente, byte[] bio01) {
		this.idBiometria = idBiometria;
		this.cliente = cliente;
		this.bio01 = bio01;
	}

	public BigInteger getIdBiometria() {
		return this.idBiometria;
	}

	public void setIdBiometria(BigInteger idBiometria) {
		this.idBiometria = idBiometria;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public byte[] getBio01() {
		return this.bio01;
	}

	public void setBio01(byte[] bio01) {
		this.bio01 = bio01;
	}

}
